export const MAX_DEVICES_PER_USER_DEFAULT = 2;
export const MONTHLY_BANDWIDTH_BYTES_DEFAULT = 50 * 1024 * 1024 * 1024; // 50 GB
export const MAX_ACTIVE_SESSIONS_DEFAULT = 2;

export const DEFAULT_VPN_PORT = 51820;
export const DEFAULT_VPN_NETWORK = '10.50.0.0/24';
export const DEFAULT_VPN_GATEWAY_IP = '10.50.0.1';
export const DEFAULT_VPN_DNS = '10.50.0.1,1.1.1.1';
export const DEFAULT_VPN_ALLOWED_IPS = '0.0.0.0/0, ::/0';
export const DEFAULT_KEEPALIVE_SECONDS = 25;

export const AUDIT_ACTIONS = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',
  USER_ACCOUNT_DELETED: 'USER_ACCOUNT_DELETED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_UNSUSPENDED: 'USER_UNSUSPENDED',
  DEVICE_CREATED: 'DEVICE_CREATED',
  DEVICE_REVOKED: 'DEVICE_REVOKED',
  PEER_PROVISIONED: 'PEER_PROVISIONED',
  PEER_REVOKED: 'PEER_REVOKED',
  IP_ALLOCATED: 'IP_ALLOCATED',
  IP_RELEASED: 'IP_RELEASED',
  GATEWAY_HEALTH_CHECK: 'GATEWAY_HEALTH_CHECK',
} as const;

export type AuditActionType = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS];
